# Generated by Django 3.0.7 on 2020-06-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFortuneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[[1, 'moon'], [2, 'sun'], [3, 'star'], [4, 'snow']], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FortuneBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[[1, 'white'], [2, 'red'], [3, 'black'], [4, 'blue']], max_length=255)),
                ('direction_choices', models.CharField(choices=[[1, 'north'], [2, 'south'], [3, 'east'], [4, 'west']], max_length=255)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fortune.UserFortuneType')),
            ],
        ),
    ]
