# Generated by Django 3.0.7 on 2020-07-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
